# Linear Algebra with Tensorflow

Leveraging almost all from this post https://biswajitsahoo1111.github.io/post/doing-linear-algebra-using-tensorflow-2/

Why do this?  

I want to get a better understanding of both Tensorflow and Linear Algebra.  So why not both?

This is leveraging the tf.linalg followed by the function name.  It's redundant, but w/e.

This mainly focuses on 1D and 2D arrays in these examples.  But TF operations are not limited to 2D arrays.  If an array has more than 2 dimensions, the matrix operation is done on the **last two** dimensions and the same operation is carried across other dimensions.  

For example a tensor of shape (3,5,5) can be thought of as 3 matrices each of shape (5,5).  When we call a matrix function on an array, the matrix function is applied to all 3 matrices of shape (5,5). The same is true for the higher dims


# Sections

- [Basics](#basics)
    * [Creating Tensors]
    * [Generating Sequences]
    * [Modifying a Tensors]
- [Matrcies]
    * [Creating Complex Matrcies]
    * [Transposing Matrcies]
    * [Creating Common Matrcies]
        * [Identity Matrix]
        * [Diagonal Matrix]
        * [Tri-diagonal Matrix]
        * [Zeros/Ones Matrix]
        * [Random Matrices]
    * [Sparse Matrcies]
- [Matrix Multi]
    * [Inner Product]
    * [Outer Product]
    * [Matrix with a Vector]
    * [Matrix with a Matrix]
    * [Two Tri-diagonal matrices]
- [More Matrix Operations]
    * [Trace]
    * [Determinant]
    * [Rank]
    * [Inverse]
    * [Extract diagonal of a matrix]
    * [Extract band part of a matrix]

In [2]:
import tensorflow as tf
print(tf.__version__)

2.3.0


## Basics

Everything revolved around `tensors`.`Tensors` are characterized by their rank.  Check out this table and the rank.

| Tensors      | Rank |
| -----------  | ----------- |
| Scalars      | Rank 0       |
| Vectors      | Rank 1        |
| Matrices     | Rank 2       |
| 3D array     | Rank 3        |

### Creating Tensors
Let's get down to business.  Starting from scalars to multi-dim arrays.  Just the real ones.

In [2]:
a = tf.constant(5.0)
a

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

Let's explain out what is shown.

1. `tf.Tensor` - this is a TF tensor 
2. `shape=()` - this is of rank 0 and therefore a scalar
3. `dtype=float32` - this defines the type of values, so a floating point value
4. `numpy` - this is the actual value of the tensor

1D `tensors` are vectors while 2D `tensors` are **matrics**

In [3]:
tf.constant([1,3,7,9])  # only one shape result is used for vectors

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 3, 7, 9])>

In [4]:
tf.constant([[1,2,3,4],
            [3,4,5,3]]) # to params are returns as (rows, columns)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [3, 4, 5, 3]])>

In [5]:
# The one above can also be defined as the following by providing a shape arg
tf.constant([1,2,3,4,5,6], shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

### Creating a sequence of numbers

Two main ways to create sequences of numbers in `Tensorflow`.  Functions `tf.range` and `tf.linspace` are used.

`Range` is an exclusive operation and will not include the last value in the range specified.

In [8]:
seq = tf.range(start=1, limit=10, delta=1)
seq.numpy()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
seq = tf.range(start=1, limit=22, delta=1.5)
seq.numpy()

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. , 11.5, 13. , 14.5, 16. ,
       17.5, 19. , 20.5], dtype=float32)

In [14]:
tf.linspace(start = 1.0, stop = 10, num = 25).numpy() 

array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ], dtype=float32)

Therefore, it's really easy to create matrices using `range` or `linspace`

In [15]:
tf.constant(tf.range(1,13), shape=(2,3,2)) # read like 2 matricies of 3 rows and 2 columns

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])>

### Slicing Tensors

This is very similar to `numpy` slicing.  By using the `[]` at the end of the vector, you can slice by row/columns

In [17]:
tf.range(1,10)[3:7].numpy() # same as the python convention of slicing.  It starts at 0 for incrementing

array([4, 5, 6, 7])

In [18]:
m = tf.constant(tf.range(20, dtype=tf.float32), shape=(4,5))
m

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]], dtype=float32)>

In [19]:
m[1:3, 2:4]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 7.,  8.],
       [12., 13.]], dtype=float32)>

### Modifying the elements of a tensor

`Tensors` are mostly immutable.  So assigning a new value by position will result in an error.

`Variable Tensors`, also defined as `tf.Variable`, can be modified after their creation.  So if you want to modify a tensor after the creation, then you must assign it to a variable.  You can also use the `assign` command.

In [22]:
var_mt = tf.Variable(tf.constant(tf.range(12, dtype=tf.float32), shape=(3,4)))
var_mt

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [23]:
# modify the matrix

var_mt[:2, 2:4].assign(-1*tf.ones(shape=(2,2)))
var_mt

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1., -1., -1.],
       [ 4.,  5., -1., -1.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

## Matrices
### Creating complex matrices

To create a complex matrix, you create the rale part and the imaginary part seperately. Then both real and imagine parts can be combined element wise to create a complex matrix.  Elements of both should be floats.

There is an easy way and a hard way

In [25]:
# Hard way
real_mat = tf.random.uniform(shape=(3,2), minval=1, maxval=5)
img_mat = tf.random.uniform(shape=(3,2), minval=1, maxval=5)

print(real_mat)
print("----------")
print(img_mat)

complex_mat = tf.dtypes.complex(real=real_mat, imag=img_mat)

print("----------")
print(complex_mat) # notice the 'j' as the stand in for i 

tf.Tensor(
[[4.2312217 2.0389304]
 [3.4727798 4.486634 ]
 [2.3664403 4.019904 ]], shape=(3, 2), dtype=float32)
----------
tf.Tensor(
[[4.520811  3.6099358]
 [3.9616013 3.2687683]
 [1.8929887 1.9107614]], shape=(3, 2), dtype=float32)
----------
tf.Tensor(
[[4.2312217+4.520811j  2.0389304+3.6099358j]
 [3.4727798+3.9616013j 4.486634 +3.2687683j]
 [2.3664403+1.8929887j 4.019904 +1.9107614j]], shape=(3, 2), dtype=complex64)


In [27]:
# easy way

complex_mat_2 = tf.constant([1+2j, 2+3j , 3+4j, 4+5j, 5+6j, 6+7j], shape = (2,3))
complex_mat_2

<tf.Tensor: shape=(2, 3), dtype=complex128, numpy=
array([[1.+2.j, 2.+3.j, 3.+4.j],
       [4.+5.j, 5.+6.j, 6.+7.j]])>

### Transposing Matrices

This is just changing the rows to columns and vice versa.  Three main functions:

* `tf.transpose`
* `tf.adjoint`
* `tf.matrix_transpose`

All the same outputs for real matrices. Complex is a different story


In [30]:
real_mat

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[4.2312217, 2.0389304],
       [3.4727798, 4.486634 ],
       [2.3664403, 4.019904 ]], dtype=float32)>

In [34]:
print(tf.transpose(real_mat).numpy())
print("---------------------")
print(tf.linalg.adjoint(real_mat).numpy())
print("---------------------")
print(tf.linalg.matrix_transpose(real_mat).numpy())
print("---------------------")

[[4.2312217 3.4727798 2.3664403]
 [2.0389304 4.486634  4.019904 ]]
---------------------
[[4.2312217 3.4727798 2.3664403]
 [2.0389304 4.486634  4.019904 ]]
---------------------
[[4.2312217 3.4727798 2.3664403]
 [2.0389304 4.486634  4.019904 ]]
---------------------


### Complex Transpose

For complex matrices, you have to conjugate transpose.  Therefore, you have to change some settings. 

`conjugate = False ` in `tf.transpose` and the other ones as well

In [35]:
complex_mat.numpy()

array([[4.2312217+4.520811j , 2.0389304+3.6099358j],
       [3.4727798+3.9616013j, 4.486634 +3.2687683j],
       [2.3664403+1.8929887j, 4.019904 +1.9107614j]], dtype=complex64)

In [40]:
tf.transpose(complex_mat, conjugate=False)

<tf.Tensor: shape=(2, 3), dtype=complex64, numpy=
array([[4.2312217+4.520811j , 3.4727798+3.9616013j, 2.3664403+1.8929887j],
       [2.0389304+3.6099358j, 4.486634 +3.2687683j, 4.019904 +1.9107614j]],
      dtype=complex64)>

### Common Matrices

Identity Matrix

In [41]:
# Identity Matrix
tf.linalg.eye(5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [43]:
# Diagonal Matrix
tf.linalg.diag([12,4,2,5,2])
# or 
tf.linalg.tensor_diag(tf.constant([1,2,3,4,5]))

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])>

In [48]:
# Diagonal but offset by one column and you can change the padding value
tf.linalg.diag([1,2,3,4,5], k=2, padding_value=-1)

<tf.Tensor: shape=(7, 7), dtype=int32, numpy=
array([[-1, -1,  1, -1, -1, -1, -1],
       [-1, -1, -1,  2, -1, -1, -1],
       [-1, -1, -1, -1,  3, -1, -1],
       [-1, -1, -1, -1, -1,  4, -1],
       [-1, -1, -1, -1, -1, -1,  5],
       [-1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1]])>

In [51]:
# You can also set it with values from other matrices
# This is very helpful because you can you the tf.constant as an array and a zeros matrix for the main shape
mat = tf.zeros((5,5))
diag = tf.constant([1,2,3,4,5.])
tf.linalg.set_diag(input = mat, diagonal = diag, k = 0)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]], dtype=float32)>

In [52]:
# Tri Diagonal Matrix

diags = tf.constant([[-1,-1,-1,-1, 0],
                     [ 2, 2, 2, 2, 2],
                     [ 0,-1,-1,-1,-1]], dtype = tf.float32)
mat = tf.zeros(shape = (5,5))
tf.linalg.set_diag(mat,diags, k = (-1,1), align = "LEFT_RIGHT")

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2., -1.,  0.,  0.,  0.],
       [-1.,  2., -1.,  0.,  0.],
       [ 0., -1.,  2., -1.,  0.],
       [ 0.,  0., -1.,  2., -1.],
       [ 0.,  0.,  0., -1.,  2.]], dtype=float32)>

In [54]:
# Zeros and Ones Matrix

tf.zeros((3,5), tf.float32)
tf.ones((3,5))

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

### Random Matrices

Create a matrix of random numbers. They are part of the `tf.random` library.  

You can create them using different distributions like

* normal
* uniform
* poisson
* gamma

In [57]:
tf.random.uniform((5,5), minval=0, maxval=5) # use the seed argument to make sure the same matrix is made each time

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1.8858194 , 0.53364575, 1.8997544 , 3.6567426 , 1.4620405 ],
       [3.2610579 , 4.785425  , 1.8729126 , 0.9660518 , 1.3561362 ],
       [3.9587462 , 0.8455205 , 4.5714307 , 4.9760494 , 4.394902  ],
       [2.4055862 , 2.2465467 , 4.5335093 , 2.974832  , 3.0581694 ],
       [1.9353604 , 2.7300525 , 0.38688362, 0.44494152, 0.0329411 ]],
      dtype=float32)>

In [59]:
# random normal
tf.random.normal((5,5), mean=1, stddev=3).numpy()

array([[ 1.327121  ,  1.0613507 ,  2.2341275 ,  4.1196747 ,  1.0428702 ],
       [ 5.8011074 ,  2.5636067 ,  2.9757242 , -1.004704  ,  2.649951  ],
       [ 4.752168  , -2.8135877 , -3.8011732 ,  0.23634845,  3.0017638 ],
       [-1.1294489 , -4.290838  ,  2.0177114 ,  1.6819851 , -0.50452435],
       [ 0.38621587,  4.6109133 ,  5.3020124 , -1.6849399 , -0.04004109]],
      dtype=float32)

a `truncated_normal` function gives values within two standard deviations of the mean on both sides of the normal curve

In [60]:
tf.random.truncated_normal((5,5), mean=0, stddev=2)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.14924651,  1.5993476 ,  0.32782015, -2.7510984 ,  0.13865246],
       [ 1.3621544 , -1.1073085 , -0.91436076, -0.6118494 ,  2.5350814 ],
       [-0.90866566, -3.0769534 ,  1.8858134 , -2.437638  , -0.8760907 ],
       [-0.43277422, -1.810705  ,  1.2931411 , -1.5736928 , -0.8064038 ],
       [ 1.9305236 ,  0.9898891 , -0.48963958,  1.1733874 ,  0.6379427 ]],
      dtype=float32)>

In [61]:
# Poisson and Gamma are also just as easy

tf.random.poisson((5,5), lam=2)
tf.random.gamma((5,5), alpha=0.7, beta=0.3)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.178757  ,  6.3228183 ,  1.0097716 ,  2.2629619 ,  4.7941027 ],
       [ 7.8373055 ,  0.42433846,  3.5918977 ,  0.42400894,  0.15884995],
       [11.289268  ,  0.08977339,  0.04302282,  1.4514136 ,  5.502763  ],
       [ 4.5758834 ,  3.4972079 ,  0.6163554 ,  1.138663  ,  6.753884  ],
       [ 3.6079593 ,  0.4600183 ,  0.45816118,  5.5687437 ,  0.1225263 ]],
      dtype=float32)>

### MORE MATRICES

you can also make `toeplitz`, `circulant`, `Kronecker

### Sparse Matrices

You have to use the `tf.spare` library.  The first argue is the indices for the values specificed in the second arguement

In [65]:
sparse_mat = tf.sparse.SparseTensor([[0,1],[1,3],[3,2]], [-5, -10, 7], dense_shape= (5,5))
sparse_mat

In [66]:
tf.sparse.to_dense(sparse_mat)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[  0,  -5,   0,   0,   0],
       [  0,   0,   0, -10,   0],
       [  0,   0,   0,   0,   0],
       [  0,   0,   7,   0,   0],
       [  0,   0,   0,   0,   0]])>

 By converting a sparse matrix into a dense one, all its special properties are lost. Therefore, sparse matrices should not be converted into dense ones.

## Matrix Multiplication

You have to use the `tf.linalg.matmul`.  Which is a lot to write. You can also use `tf.matmul`

Inputs to `tf.linalg.matmul` are matrices.  Therefore, while multiplying the inputs are matrices.  So while multiplying to arrays, you have to convert them into vectors and then multipled

### Two column vectors

In [75]:
v1 = tf.constant([1,2,3,4], shape=(4,1), dtype=tf.float32)
v2 = tf.constant([1,2,3,4], shape=(4,1), dtype=tf.float32)

tf.matmul(v1,v2,transpose_a=True).numpy() # inner product

array([[30.]], dtype=float32)

In [76]:
tf.matmul(v1,v2,transpose_b=True).numpy() # inner product

array([[ 1.,  2.,  3.,  4.],
       [ 2.,  4.,  6.,  8.],
       [ 3.,  6.,  9., 12.],
       [ 4.,  8., 12., 16.]], dtype=float32)

### Multiplying a matrix and vector

You can use `tf.linalg.matvec`.  OR do the long way of converting the vector into a column vector and then apply `tf.matmul`

In [78]:
mat_1 = tf.constant([1,2,3,4,5,6],shape = (2,3), dtype = tf.float32)
vector_1 = tf.constant([1., 2., 3.], shape = (3,1))
mat_1.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [79]:
tf.matmul(a = mat_1, b = vector_1).numpy()

array([[14.],
       [32.]], dtype=float32)

In [80]:
tf.linalg.matvec(mat_1, tf.constant([1,2,3.]))    # Note the shape of input vector and result.

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([14., 32.], dtype=float32)>

In [81]:
## Multiplying two matrices

tf.linalg.matmul(a = mat, b = mat, transpose_a=True).numpy() # Without `transpose_a` argument, result will be an error.

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)